use_frameworks!

platform :ios, '11.0'

target 'CircleProgressChart_Example' do
  pod 'CircleProgressChart', :path => '../'

  target 'CircleProgressChart_Tests' do
    inherit! :search_paths

    
  end
end
